### ISSUE TITLE
OSError: ./EllipseFitError.dll: invalid ELF header

### ISSUE THREAD

**Issue by huaji98** [cuneytakinlar/pupil-ellipse-fit-error#1]
python trainUNet.py
Traceback (most recent call last):
  File "trainUNet.py", line 17, in <module>
    from ellipseFitError import EllipseFitErrorUNet
  File "/home/user/pupil-ellipse-fit-error/ellipseFitError.py", line 7, in <module>
    ellipseFitErrorDll = CDLL("./EllipseFitError.dll")
  File "/home/user/anaconda3/envs/master/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./EllipseFitError.dll: invalid ELF header

**Comment by huaji98** [comment]
I also run in Windows ,than 
OSError: [WinError 126] The specified module could not be found

**Comment by cuneytakinlar** [comment]
Make sure that the directory where the DLL is located is in your Windows System Path

**Comment by huaji98** [comment]
Thanks，I solve it，just unzip “opencv_world340.rar”
